### ISSUE TITLE
Problem: users cannot track time spent on tasks

### ISSUE THREAD

**Issue by gsovereignty** [EmurgoHK/emurgolance#1]
Problem: users cannot track time spent on tasks

A solution should include the following: 
- URL field for github issue being worked on.
- a stopwatch. E.g. users click 'start work' after putting in the issue URL and it starts ticking. When they are finished, they click "done" or whatever to stop the timer. This time is automatically logged in their timesheet. A pause button is probably also a good idea.

Once "done" is clicked a confirmation or something should probably be shown.

ping @ashhimself @anbud @samuelralak

**Comment by AshHimself** [comment]
If this is related to timesheets then should an option exist to pause or manually adjust? I understand the driver to this requirement but in reality people never click start and then stop when finished. Things get in the way or people forget what they are doing.

**Comment by gsovereignty** [comment]
> in reality people never click start and then stop when finished

In Blockrazor about 80% of people do, but yeah we have to take into account the people who don't work that way.

Manually editing could be done in this issue or added as a new issue after this one is solved, it's basically the same at this early point in the project.

**Comment by anbud** [comment]
I'm in that 80%, but I agree that manual editing/adding should be implemented as well.

Claiming this one. :)

**Comment by anbud** [comment]
Basic functionality is implemented in #2. Manually adjusting times should be logged as an another issue.

I've taken most of the UI from Emurgis to make it look a little bit nicer, but it probably needs some UI love. I haven't implemented real error handling (errors are just logged in the console for now) since we still have to decide what error display mechanism should we use.

I've used `accounts-ui` and `accounts-password` for a simple auth system.
